### ISSUE TITLE
Rod of Lordly Might has an incorrect description (missing Spear / button #3).

### ISSUE THREAD

**Issue by slaapliedje** [Alby1987/AD-DCoreRule2.0Errata#1]
It looks like there was a mistake in transcribing the description for the Rod of Lordly Might description, and it skips button #3.
`
battle axe +4 when button #2 is pushed. The sword blade springs forth, and the handle can be lengthened up to 12 feet, for an overall length of from 6 to 15 feet. In 15-foot length, the rod is suitable for use as a lance.
`
Should read as
`battle axe +4 when button #2 is pushed. Again, a blade springs forth at the ball, and the whole lengthens to a length of four feet.
spear +3 when button #3 is pushed. The sword blade springs forth, and the handle can be lengthened up to 12 feet, for an overall length of from 6 feet to 15 feet. In 15-foot length, the rod is suitable for use as a lance. `

**Comment by Alby1987** [comment]
You're right. This is not an errata of the books, but of the online books. Already patched, will publish the fix soon.
